# Generated by Django 6.0 on 2026-03-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="useraccount",
            fields=[
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.IntegerField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("employee", "Employee"), ("jobseeker", "JobSeeker")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
