# Generated by Django 6.0 on 2026-03-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="first_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="last_name",
            new_name="lastname",
        ),
    ]
