# Generated by Django 6.0.3 on 2026-03-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_first_name_useraccount_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='password', max_length=128),
            preserve_default=False,
        ),
    ]
