# Generated by Django 6.0 on 2026-03-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
